export const tenantDetails = [
  {
    id: 1,
    title: "2 Bedroom Apartment in Lekki",
    address: "Lekki Phase 1, Lagos",
    propertyType: "Self Contained",
    images: [
      "/images/heropic1.png",
      "/images/section2a.png",
      "/images/section2a.png",
    ],
    tenants: [
      {
        profileImage: "",
        name: "Adam Smith",
        unit: "1",
        paymentStatus: "Owing",
        moveInDate: "Feb 20, 2025",
        activeStatus: "Offline",
        phone: "+234567890123",
        email: "renty@gmail.com",
        propertyAssigned: "Gbagada Apartment - Flat 1",
        occupation: "Banker",
        company: "Zenith Bank",
        maritalStatus: "Single",
        stateOfOrigin: "Oyo State",
        nationality: "Nigerian",
        governmentID: "NIN",
        leaseDuration: "12 months",
        emergencyName: "Dayo Amusan",
        emergencyContact: "+234123456789",
        payments: [
          {
            year: "2024 - 2025",
            amount: "350,000",
            status: "Paid",
            datePaid: "Feb 20, 2025",
          },
          {
            year: "2025 - 2026",
            amount: "350,000",
            status: "Pending",
            datePaid: "",
          },
        ],
      },
      {
        profileImage: "",
        name: "James Dag",
        unit: "2",
        paymentStatus: "Paid",
        moveInDate: "Feb 20, 2025",
        activeStatus: "Online",
        phone: "+234567890123",
        email: "renty120@gmail.com",
        propertyAssigned: "Gbagada Apartment - Flat 2",
        occupation: "Banker",
        company: "Zenith Bank",
        maritalStatus: "Single",
        stateOfOrigin: "Oyo State",
        nationality: "Nigerian",
        governmentID: "NIN",
        leaseDuration: "12 months",
        emergencyName: "Dayo Amusan",
        emergencyContact: "+234123456789",
        payments: [
          {
            year: "2024 - 2025",
            amount: "350,000",
            status: "Paid",
            datePaid: "Feb 20, 2025",
          },
          {
            year: "2025 - 2026",
            amount: "350,000",
            status: "Pending",
            datePaid: "",
          },
        ],
      },
    ],
  },
];
